### PR TITLE
Sprint 2 Release - Backend

### PR DESCRIPTION
**Pull request by jsurrea**
This release includes the development of the AvailableSpaces service, which is currently deployed in Compute Engine instances of GCP at http://34.133.121.100:3000/ 

The details of this new service are specified in the following PR: https://github.com/ISIS3510-202410-Team-13/Backend/pull/2

### CODE REVIEW

**Comment by jsurrea** [comment]
I believe we're ready to deploy Backend, wdyt? @jdcastellanosb73 @SnowArtz @Laudarias @iGotty

**Review by jdcastellanosb73 — APPROVED** [review]

**Comment by SnowArtz** [comment]
> I believe we're ready to deploy Backend, wdyt? @jdcastellanosb73 @SnowArtz @Laudarias @iGotty

It looks nice for me! I think we are ready! :D

**Review by SnowArtz — APPROVED** [review]
Perfect! Lets do it!

**Review by iGotty — APPROVED** [review]

**Review by Laudarias — APPROVED** [review]
Ok!

**Pull request merged**
